### ISSUE TITLE
bug - freezes at name choosing on game over screen

### ISSUE THREAD

**Issue by safarirat** [akouzoukos/apotris#3]
3.4.1 
old save file from v. 3.2

replication process:
Start new game > lost > name field is blank (sus) > typing my name > "enter" > freeze
reload
Start new game > lost > name field is safa > "enter" > freeze

same behaviour on hardware (omega de) and emulator.
Thanks
![изображение](https://user-images.githubusercontent.com/23118902/202274388-626703ce-618d-4b50-93d0-3d8344c516e8.png)
![изображение](https://user-images.githubusercontent.com/23118902/202274410-17d22202-8cc8-418a-bf8d-fc7e22b658b4.png)
My save file. (rename Copy (1) apotris.txt.sav to apotris.txt)
[Copy (1) apotris.txt](https://github.com/akouzoukos/apotris/files/10025049/Copy.1.apotris.txt)

**Comment by akouzoukos** [comment]
Ah sorry about that, it looks like I messed up save conversion from updates 3.2 and before. Here's the fixed save file. 
[apotris-save-fixed.txt](https://github.com/akouzoukos/apotris/files/10025212/apotris-save-fixed.txt)

For the time being if anyone else has this issue, you can fix the save file by first running it through v3.3 and then playing normally with v3.4.1

**Comment by safarirat** [comment]
Thanks! ❤
