### ISSUE TITLE
Glitched text from enabling rumble

### ISSUE THREAD

**Issue by MelloBoo44** [akouzoukos/apotris#6]
Reproduced on 4.0.1 and 4.0.2 (on GBA emulators)
If rumble is already enabled, disable it and restart the game.

Then, open settings -> handling, back out to the main settings menu, then controls, and enable rumble and save.

https://github.com/akouzoukos/apotris/assets/97173040/1f48e62c-f59a-45f0-9fea-3317588d5440

**Comment by akouzoukos** [comment]
Thanks, fixed
