### ISSUE TITLE
up arrow seems to occasionally be firing again immediately after a hard drop

### ISSUE THREAD

**Issue by jerwarren** [akouzoukos/apotris#9]
Playing on two different devices (Anbernic RG351M and Analogue Pocket) I've been having an issue with two pieces hard-dropping instead of one occasionally when hitting the up arrow. This doesn't happen in any other Tetris games, and I'm hopeful this can be resolved. It doesn't do it all the time, but it does it enough to be maddening. My assumption is that it's a timing issue, where the piece is dropped before the button is unpressed, causing another hard drop. I absolutely love how little delay there is between drops/clears before the next piece is playable, but it feels a little bit like maybe that's part of the problem?

**Comment by akouzoukos** [comment]
There can be a couple of causes for this. Usually it's the physical switches on the controller registering twice. Old games usually have entry delay (delay before the next piece appears) to prevent this. Apotris has the "drop protection" option in Settings > Handling which stops dropping for X frames after placing a piece. Try increasing the value for that setting to see if your issue goes away.

If you're using the SOFT "disable diagonals" option in Settings > Handling, that could also be causing double drops, so try the HARD or OFF options too.

**Comment by jerwarren** [comment]
Thank you for your help. I feel silly for not having even looked to see if this was configurable, but increasing drop protection did the trick. (This is a truly excellent Tetris.)
